# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('aqua-sim-example', ['aqua-sim'])
    obj.source = 'aqua-sim-example.cc'

